### ISSUE TITLE
[FEATURE] Remove "Overview" heading from specific pages

### ISSUE THREAD

**Issue by melissahenderson** [interledger/docs-design-system#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What type of enhancement are you suggesting?

Elevate project-specific component to shared

### Is your feature request related to a problem? Please describe.

Starlight automatically includes an "Overview" heading at top of each page's table of contents. Starlight does not provide a native way hide "Overview" or change the wording. The Overview heading is unnecessary for some pages, such as a glossary page. The heading shows up in the page's table of contents regardless. 

### Describe the solution you'd like

HJ implemented a solution for the Web Monetization documentation; however, all of our customer-facing doc sites have (or should have) a glossary. There are other instances -- such as when the content of a page is very short -- where having the Overview heading is unnecessary. 

I'd like for HJ's solution, or something similar if you prefer, to be available to all of our doc sites. 

### Additional context

The files used in the Web Monetization site are:
- components/docs/PageSidebar.astro (this is where we list pages that should exclude the Overview heading)
- components/docs/shared/removeoverview.mdx (how it works; the April 30, 2024 note should be removed because it's not just in my local branch anymore)

**Comment by JoblersTune** [comment]
Implemented this on a per page basis. Please close this issue when you are happy with the respective site's changes :)
